# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
