# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170908_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.TextField(max_length=128),
        ),
    ]
